### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by realityking** [Raynos/reduce#9]
It'd be great to have a new version of `reduce` tagged & release that includes c929e4f263bfc2f4512ea3126cf5460f4d5bfa2c

It'd allow deduplicating `object-keys` in my bundle and make things a little smaller ❤️

**Comment by ljharb** [comment]
Sure, I can do that in the next day or three.

**Comment by ljharb** [comment]
v1.0.2 released.

**Comment by realityking** [comment]
Thank you!
